repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml

  - repo: local
    hooks:
      - id: clang-format
        name: clang-format
        description: runs clang-format on a predefined sets of files
        language: system
        entry: clang-format -i
        types_or: [ c++ ]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml

  - repo: https://github.com/psf/black
    rev: 26.3.1
    hooks:
      - id: black
        language_version: python3

  - repo: https://github.com/pycqa/isort
    rev: 8.0.1
    hooks:
      - id: isort
